MedicalAppointment.Web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointment.Web.Controllers
{
    [Route("Access/Login")]
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

MedicalAppointment.Web/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointment.Web.Controllers
{
    [Route("Access/SignIn")]
    public class RegisterController : Controller
    {
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        //[HttpPost]
        //public Task<IActionResult> Register(PatientUserModel user)
        //{
        //    return View();
        //}
    }
}

MedicalAppointment.Web/Views/Login/Login.cshtml
@model LoginModel

<div class="row mt-5 justify-content-center">
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header">
                <h2>Registrarse</h2>
            </div>
            <div class="card-body">
                <form asp-controller="Register" asp-action="Register" method="post">
                    <input class="form-control mb-3" type="text" required placeholder="Correo Electrónico" asp-for="Email" />
                    <input class="form-control mb-3" type="password" required placeholder="Contraseña" asp-for="Password" />
                    <div class="d-grid gap-2 mb-3">
                        <button class="btn btn-primary" type="submit">Registrarse</button>
                    </div>
                    <p>¿Ya tienes una cuenta? <a asp-controller="Login" asp-action="Login">Iniciar sesión</a></p>
                </form>
            </div>
        </div>
    </div>
</div>